# Generated by Django 4.2.7 on 2024-09-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='creators',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='description_file',
            field=models.FileField(null=True, upload_to='description_files'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
