# Generated by Django 4.2.7 on 2024-09-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_song_creators_song_date_song_description_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='description_files'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='songs_files'),
        ),
    ]
